// Exercicios-WEB/react/calculadora/src/components/Button.jsx
/* Aula 3 - React - Projeto Calculadora: Componente Button #01 */


import React from "react"
import './Button.css'


export default props => {
    let classes = 'button '
    classes += props.operation ? 'operation' : ''
    classes += props.double ? 'double' : ''
    classes += props.triple ? 'triple' : ''
    
    return (
        <button 
            onClick={e => props.click && props.click(props.label)}
            className={classes}>
            {props.label}
        </button>
    )
}


/*export default props => {
    let classes = 'button'
    classes +=  props.operation ? 'operation' : ''
    classes +=  props.double ? 'double' : ''
    classes += props.triple ? 'triple' : ''
    
    return (
        <button
            onClick={e => props.click && props.click(props.label)}
            className={classes}>
            {props.label}
        </button>

    )
}*/




/*export default props => (
  <button
    className={`
        button
        ${props.operation} ? 'operation' : ''}
        ${props.double} ? 'double' : ''}
        ${props.triple} ? 'triple' : ''}
    `}
    onClick={e => props.click && props.click(props.label)} // props.lable
  >
    {props.label}
  </button>
)
   */

// Exercicios-WEB/vue/calculator/src/components/ButtonComponent.vue
<!-- Aula 3 - Projeto Calculadora (Vue): Criando Componentes -->
<!-- Aula 4 - Projeto Calculadora (Vue): Componente Button #01 -->

<template>
    <button class="button"
        :class="{double, triple, operation}">
        {{ label }}
    </button>
</template>

<script>
export default {
    props: {
        label: {},
        operation: { type: Boolean},
        double: { type: Boolean}, 
        triple: { type: Boolean}    
    
    }
  

}
</script>

<style>
:root {
    --bg-button: #f0f0f0;
    --border-button: solid 1px #888;
}

.button {
    font-size: 1.4em;
    background-color: var(--bg-button);
    border: none;
    border-right: var(--border-button);
    border-bottom: var(--border-button);
    outline: none;
    
}

.button:active {
    background-color: #ccc;
}

.button.double {
    grid-column: span 2;
}

.button.triple {
    grid-column: span 3;
}

.button.operation {
    background-color: #fa8231;
    color: #fff;
    
}

.button.button.operation:active {
    background-color: #fa8231cc;
}

</style>
